version: "3.8"

services:
  wiki_db:
    image: postgres:15
    env_file: wiki_db.env
    restart: always
    logging:
      driver: "none"
    volumes:
      - "./data/wiki/db:/var/lib/postgresql/data"
    networks:
      - wiki_db
  wiki:
    image: requarks/wiki:2
    env_file: wiki.env
    restart: always
    depends_on:
      - wiki_db
    networks:
      - wiki_db
      - nginx

  tickets_db:
    image: postgres:15
    env_file: tickets_db.env
    restart: always
    logging:
      driver: "none"
    volumes:
      - "./data/tickets/db:/var/lib/postgresql/data"
    networks:
      tickets_internal:
        aliases:
          - db
  tickets_web:
    image: rotheross/otobo:rel-10_0_9
    restart: always
    env_file: tickets.env
    cap_drop:
        - ALL
    depends_on:
      - tickets_db
      - tickets_redis
    expose:
      - 5000
    volumes:
      - "./data/tickets/data:/opt/otobo"
    command: web
    networks:
      nginx:
      tickets_internal:
        aliases:
          - web
  tickets_daemon:
    image: rotheross/otobo:rel-10_0_9
    restart: always
    env_file: tickets.env
    cap_drop:
        - ALL
    depends_on:
      - tickets_web
    volumes:
      - "./data/tickets/data:/opt/otobo"
    command: daemon
    networks:
      tickets_internal:
        aliases:
          - daemon
  tickets_redis:
    image: redis:6.0.8-alpine
    restart: always
    user: redis:redis
    cap_drop:
        - ALL
    volumes:
      - "./data/tickets/reds:/data"
    networks:
      tickets_internal:
        aliases:
          - redis

  weblate_db:
    image: postgres:15-alpine
    env_file:
      - ./weblate.env
    volumes:
      - "./data/weblate/db:/var/lib/postgresql/data"
    restart: always
    networks:
      - weblate_internal
  weblate_cache:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "./data/weblate/redis:/data"
    networks:
      - weblate_internal
    networks:
      weblate_internal:
        aliases:
          - redis
  weblate:
    image: weblate/weblate:4.12.1-1
    tmpfs:
      - /app/cache
    volumes:
      - "./data/weblate/data:/app/data"
    env_file:
      - ./weblate.env
    restart: always
    depends_on:
      - weblate_db
      - weblate_cache
    networks:
      - weblate_internal
      - nginx


  nginx:
    build: nginx
    env_file: nginx.env
    restart: always
    volumes:
      - "./data/certs/:/certs/"
      - "./data/nginx/logs/:/var/log/nginx/"
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
networks:
  wiki_db:
    driver: bridge
  nginx:
    driver: bridge
  tickets_internal:
    driver: bridge
  weblate_internal:
    driver: bridge
