version: "3"
services:
  wikidb:
    image: postgres:13
    env_file: wikidb.env
    restart: always
    logging:
      driver: "none"
    volumes:
      - "./data/wiki:/var/lib/postgresql/data"
    networks:
      - wikidb
  wiki:
    image: requarks/wiki:2
    env_file: wiki.env
    restart: always
    depends_on:
      - wikidb
    #  - 3000:3000
    networks:
      - wikidb
      - nginx
  nginx:
    build: nginx
    env_file: nginx.env
    restart: always
    volumes:
      - "./data/certs/:/certs/"
      - "./data/nginx/logs/:/var/log/nginx/"
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
networks:
  wikidb:
    driver: bridge
  nginx:
    driver: bridge
